spring:
  application:
    name: ConsumerApp
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://eurekaService7001.com:7001/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}


info:
  app.name: wzx_ConsumerApp
  company.name: www.wzx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$